matrix:
  include:
    - language: objective-c
      os: osx
      xcode_workspace: './ios/SwiftStaff.xcworkspace'
      xcode_scheme: SwiftStaff
      xcode_sdk: iphonesimulator13.4
      osx_image: xcode11.4
      podfile: ios/Podfile
      node_js: false
      sudo: true
      before_install:
        - echo "before_install"
      install:
        - echo "install"
      script:
        - echo "script"
    - language: android
      android:
        components:
          - tools
          - platform-tools
      sudo: true
      before_install:
        - echo "android before_install"
      install:
        - echo "android install"
      script:
        - echo "android script"
    - if: branch = master
      language: node_js
      node_js: lts/*
      install: true
      script: echo "MASTER BRANCH"
