os: osx
osx_image: xcode11.4
jdk:
  - oraclejdk8
  - openjdk8
language: node_js
node_js:
  - "14"
addons:
  homebrew:
    packages:
      - watchman
    casks:
      - adoptopenjdk/openjdk/adoptopenjdk8
      - android-sdk
jobs:
  include:
    - stage: Unit Test
      script: npm test
    - stage: Generate and Deploy
      script: cd android && ./gradlew assembleRelease && ls -al ./app/build/outputs/apk/release && cd .. && npm run upload

before_install:
  - npm i -g
  - export ANDROID_HOME=/usr/local/share/android-sdk
  - export PATH=$PATH:$ANDROID_HOME/emulator
  - export PATH=$PATH:$ANDROID_HOME/tools
  - export PATH=$PATH:$ANDROID_HOME/tools/bin
  - export PATH=$PATH:$ANDROID_HOME/platform-tools
  - export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
  - yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses


