os: osx
osx_image: xcode11.4
language: node_js
node_js:
  - "14"
addons:
  homebrew:
    packages:
      - watchman
    casks:
      - adoptopenjdk/openjdk/adoptopenjdk8
      - android-sdk
jobs:
  include:
    - stage: Unit Test
      script: npm test
    - stage: Deploy
      script: react-native run-android --variant=release && ls -al ./android/app/build/outputs/apk/release

before_install:
  - npm i -g
  - export ANDROID_HOME=/usr/local/share/android-sdk
  - export PATH=$PATH:$ANDROID_HOME/emulator
  - export PATH=$PATH:$ANDROID_HOME/tools
  - export PATH=$PATH:$ANDROID_HOME/tools/bin
  - export PATH=$PATH:$ANDROID_HOME/platform-tools

